version: "3"
services:
  grafana:
    build: 
      context: './grafana/'
    container_name: grafana
    #image: grafana/grafana:latest
    ports:
      - 80:3000
    volumes:
      - ./grafana/data:/home/grafana/data:rw
      - ./grafana/conf/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    environment:
    #  - GF_INSTALL_PLUGINS=grafana-worldmap-panel
       - GF_PATHS_DATA=/home/grafana/data
    depends_on:   
      - postgres
  postgres:
    build:
      context: './postgres/'
    #image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init/dbinit.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./postgres/initdata:/tmp:ro
      #- ./postgres/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
  cron:
    build: 
      context: './cron/'
    depends_on: 
      - postgres
    volumes:
      - ./cron/schedules.crontab:/schedules.crontab
  after-init:
    build:
      context: './after-init/'
    depends_on: 
      - postgres
      - cron
      - grafana
    restart: on-failure:500
    

